import { PhoneModel } from './types';

export const PHONE_MODELS: PhoneModel[] = [
  // --- APPLE iPHONE (Device Dimensions) ---
  {
    id: 'iphone-16-pro-max',
    brand: 'Apple',
    name: 'iPhone 16 Pro Max',
    widthMm: 77.6,
    heightMm: 163.0,
    cornerRadiusMm: 12,
    camera: { xMm: 5, yMm: 5, widthMm: 40, heightMm: 42, cornerRadiusMm: 10 },
  },
  {
    id: 'iphone-16-pro',
    brand: 'Apple',
    name: 'iPhone 16 Pro',
    widthMm: 71.5,
    heightMm: 149.6,
    cornerRadiusMm: 11,
    camera: { xMm: 5, yMm: 5, widthMm: 35, heightMm: 37, cornerRadiusMm: 8 },
  },
  {
    id: 'iphone-16-plus',
    brand: 'Apple',
    name: 'iPhone 16 Plus',
    widthMm: 77.8,
    heightMm: 160.9,
    cornerRadiusMm: 11,
    camera: { xMm: 5, yMm: 5, widthMm: 30, heightMm: 30, cornerRadiusMm: 7 },
  },
  {
    id: 'iphone-16',
    brand: 'Apple',
    name: 'iPhone 16',
    widthMm: 71.6,
    heightMm: 147.6,
    cornerRadiusMm: 11,
    camera: { xMm: 5, yMm: 5, widthMm: 30, heightMm: 30, cornerRadiusMm: 7 },
  },
  {
    id: 'iphone-17-pro-max',
    brand: 'Apple',
    name: 'iPhone 17 Pro Max',
    widthMm: 77.6,
    heightMm: 163.0,
    cornerRadiusMm: 12,
    camera: { xMm: 5, yMm: 5, widthMm: 40, heightMm: 42, cornerRadiusMm: 10 },
  },
  {
    id: 'iphone-17-pro',
    brand: 'Apple',
    name: 'iPhone 17 Pro',
    widthMm: 71.5,
    heightMm: 149.6,
    cornerRadiusMm: 11,
    camera: { xMm: 5, yMm: 5, widthMm: 35, heightMm: 37, cornerRadiusMm: 8 },
  },
  {
    id: 'iphone-17-plus',
    brand: 'Apple',
    name: 'iPhone 17 Plus',
    widthMm: 77.8,
    heightMm: 160.9,
    cornerRadiusMm: 11,
    camera: { xMm: 5, yMm: 5, widthMm: 30, heightMm: 30, cornerRadiusMm: 7 },
  },
  {
    id: 'iphone-17',
    brand: 'Apple',
    name: 'iPhone 17',
    widthMm: 71.6,
    heightMm: 147.9,
    cornerRadiusMm: 11,
    camera: { xMm: 5, yMm: 5, widthMm: 32, heightMm: 32, cornerRadiusMm: 8 },
  },

  // --- APPLE iPHONE PLATES (Sublimation) ---
  {
    id: 'iphone-15-16-pro-max-plate',
    brand: 'Apple',
    name: 'iPhone 15 / 16 Pro Max (Placa)',
    widthMm: 73.0,
    heightMm: 155.5,
    cornerRadiusMm: 11,
    camera: { xMm: 4, yMm: 4, widthMm: 38, heightMm: 40, cornerRadiusMm: 9 },
  },
  {
    id: 'iphone-12-13-14-pro-max-plate',
    brand: 'Apple',
    name: 'iPhone 12 / 13 / 14 Pro Max (Placa)',
    widthMm: 74.0,
    heightMm: 156.5,
    cornerRadiusMm: 11,
    camera: { xMm: 4, yMm: 4, widthMm: 38, heightMm: 40, cornerRadiusMm: 9 },
  },
  {
    id: 'iphone-13-14-pro-plate',
    brand: 'Apple',
    name: 'iPhone 13 Pro / 14 Pro (Placa)',
    widthMm: 68.0,
    heightMm: 143.5,
    cornerRadiusMm: 11,
    camera: { xMm: 4, yMm: 4, widthMm: 35, heightMm: 37, cornerRadiusMm: 8 },
  },
  {
    id: 'iphone-12-13-14-plate',
    brand: 'Apple',
    name: 'iPhone 12 / 12 Pro / 13 / 14 (Placa)',
    widthMm: 67.5,
    heightMm: 142.5,
    cornerRadiusMm: 11,
    camera: { xMm: 4, yMm: 4, widthMm: 30, heightMm: 30, cornerRadiusMm: 7 },
  },
  {
    id: 'iphone-xr-11-plate',
    brand: 'Apple',
    name: 'iPhone XR / 11 (Placa)',
    widthMm: 71.5,
    heightMm: 146.5,
    cornerRadiusMm: 12,
    camera: { xMm: 5, yMm: 5, widthMm: 30, heightMm: 35, cornerRadiusMm: 8 },
  },
  {
    id: 'iphone-x-xs-plate',
    brand: 'Apple',
    name: 'iPhone X / XS (Placa)',
    widthMm: 67.0,
    heightMm: 139.5,
    cornerRadiusMm: 11,
    camera: { xMm: 5, yMm: 5, widthMm: 25, heightMm: 35, cornerRadiusMm: 12 },
  },
  {
    id: 'iphone-6-7-8-se-plate',
    brand: 'Apple',
    name: 'iPhone 6 / 7 / 8 / SE (Placa)',
    widthMm: 63.2,
    heightMm: 134.5,
    cornerRadiusMm: 10,
    camera: { xMm: 5, yMm: 5, widthMm: 20, heightMm: 20, cornerRadiusMm: 10 },
  },
  {
    id: 'iphone-6-7-8-plus-plate',
    brand: 'Apple',
    name: 'iPhone 6+ / 7+ / 8+ (Placa)',
    widthMm: 73.5,
    heightMm: 153.5,
    cornerRadiusMm: 10,
    camera: { xMm: 5, yMm: 5, widthMm: 35, heightMm: 20, cornerRadiusMm: 10 },
  },

  // --- APPLE iPAD (Device Dimensions) ---
  {
    id: 'ipad-pro-13-m4',
    brand: 'Apple',
    name: 'iPad Pro 13" (M4 / 7.ª Gen)',
    widthMm: 214.9,
    heightMm: 280.6,
    cornerRadiusMm: 20,
    camera: { xMm: 10, yMm: 10, widthMm: 30, heightMm: 30, cornerRadiusMm: 5 },
  },
  {
    id: 'ipad-pro-11-m4',
    brand: 'Apple',
    name: 'iPad Pro 11" (M4 / 7.ª Gen)',
    widthMm: 178.5,
    heightMm: 247.6,
    cornerRadiusMm: 18,
    camera: { xMm: 10, yMm: 10, widthMm: 25, heightMm: 25, cornerRadiusMm: 5 },
  },
  {
    id: 'ipad-10-11-gen',
    brand: 'Apple',
    name: 'iPad 10 / 11 (10.9")',
    widthMm: 179.5,
    heightMm: 248.6,
    cornerRadiusMm: 15,
    camera: { xMm: 10, yMm: 10, widthMm: 20, heightMm: 20, cornerRadiusMm: 10 },
  },
  {
    id: 'ipad-7-8-9-gen',
    brand: 'Apple',
    name: 'iPad 7 / 8 / 9 (10.2")',
    widthMm: 174.1,
    heightMm: 250.6,
    cornerRadiusMm: 12,
    camera: { xMm: 10, yMm: 10, widthMm: 15, heightMm: 15, cornerRadiusMm: 7 },
  },
  {
    id: 'ipad-5-6-gen',
    brand: 'Apple',
    name: 'iPad 5 / 6 (9.7")',
    widthMm: 169.5,
    heightMm: 240.0,
    cornerRadiusMm: 12,
    camera: { xMm: 10, yMm: 10, widthMm: 15, heightMm: 15, cornerRadiusMm: 7 },
  },
  {
    id: 'ipad-2-3-4-gen',
    brand: 'Apple',
    name: 'iPad 2 / 3 / 4 (9.7")',
    widthMm: 185.7,
    heightMm: 241.2,
    cornerRadiusMm: 10,
    camera: { xMm: 10, yMm: 10, widthMm: 20, heightMm: 20, cornerRadiusMm: 10 },
  },
  {
    id: 'ipad-1-gen',
    brand: 'Apple',
    name: 'iPad 1 (9.7")',
    widthMm: 189.7,
    heightMm: 242.8,
    cornerRadiusMm: 8,
    camera: { xMm: 10, yMm: 10, widthMm: 20, heightMm: 20, cornerRadiusMm: 10 },
  },
  {
    id: 'ipad-mini-6-7',
    brand: 'Apple',
    name: 'iPad mini 6 / 7 (8.3")',
    widthMm: 134.8,
    heightMm: 195.4,
    cornerRadiusMm: 15,
    camera: { xMm: 8, yMm: 8, widthMm: 15, heightMm: 15, cornerRadiusMm: 7 },
  },

  // --- SAMSUNG PLATES ---
  {
    id: 'samsung-s24-s25-s26-ultra-plate',
    brand: 'Samsung',
    name: 'Galaxy S24 / S25 / S26 Ultra (Placa)',
    widthMm: 74.0,
    heightMm: 158.5,
    cornerRadiusMm: 2,
    camera: { xMm: 8, yMm: 8, widthMm: 30, heightMm: 55, cornerRadiusMm: 4 },
  },
  {
    id: 'samsung-s24-s25-s26-plus-plate',
    brand: 'Samsung',
    name: 'Galaxy S24+ / S25+ / S26+ (Placa)',
    widthMm: 71.5,
    heightMm: 153.5,
    cornerRadiusMm: 10,
    camera: { xMm: 8, yMm: 8, widthMm: 25, heightMm: 50, cornerRadiusMm: 12 },
  },
  {
    id: 'samsung-s24-s25-s26-plate',
    brand: 'Samsung',
    name: 'Galaxy S24 / S25 / S26 (Placa)',
    widthMm: 66.2,
    heightMm: 141.5,
    cornerRadiusMm: 10,
    camera: { xMm: 8, yMm: 8, widthMm: 20, heightMm: 45, cornerRadiusMm: 10 },
  },

  // --- XIAOMI / REDMI PLATES ---
  {
    id: 'xiaomi-14-15-plate',
    brand: 'Xiaomi',
    name: 'Xiaomi 14 / 15 (Placa)',
    widthMm: 66.5,
    heightMm: 146.5,
    cornerRadiusMm: 10,
    camera: { xMm: 8, yMm: 8, widthMm: 40, heightMm: 40, cornerRadiusMm: 8 },
  },
  {
    id: 'xiaomi-14-15-pro-plate',
    brand: 'Xiaomi',
    name: 'Xiaomi 14 Pro / 15 Pro (Placa)',
    widthMm: 71.0,
    heightMm: 155.5,
    cornerRadiusMm: 10,
    camera: { xMm: 8, yMm: 8, widthMm: 45, heightMm: 45, cornerRadiusMm: 8 },
  },
  {
    id: 'redmi-note-13-14-pro-5g-plate',
    brand: 'Xiaomi',
    name: 'Redmi Note 13 / 14 Pro 5G (Placa)',
    widthMm: 70.0,
    heightMm: 157.0,
    cornerRadiusMm: 10,
    camera: { xMm: 8, yMm: 8, widthMm: 40, heightMm: 40, cornerRadiusMm: 8 },
  },

  // --- OPPO PLATES ---
  {
    id: 'oppo-reno-12-pro-plate',
    brand: 'Oppo',
    name: 'Oppo Reno 12 / 12 Pro (Placa)',
    widthMm: 70.0,
    heightMm: 156.0,
    cornerRadiusMm: 10,
    camera: { xMm: 8, yMm: 8, widthMm: 30, heightMm: 50, cornerRadiusMm: 10 },
  },
  {
    id: 'oppo-reno-13-pro-plate',
    brand: 'Oppo',
    name: 'Oppo Reno 13 / 13 Pro (Placa)',
    widthMm: 71.5,
    heightMm: 157.5,
    cornerRadiusMm: 10,
    camera: { xMm: 8, yMm: 8, widthMm: 30, heightMm: 50, cornerRadiusMm: 10 },
  },
];


export const MM_TO_PX = 3.7795275591; // 1mm = 3.78px at 96 DPI
export const EXPORT_DPI = 300;
export const MM_TO_PX_EXPORT = EXPORT_DPI / 25.4; // 1mm = 11.81px at 300 DPI
